title: <p align="center"> Santhosh Rameshkumar </p>
logo: /assets/img/logo.png
description:
       <p align="center"> 
       <br>
       In recent times, I started working on Computational Approaches mainly informatics for Research & Development in Science & Engineering.
       </br>
       </p>

theme: jekyll-theme-minimal
